/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;

public class App {

    public static void main(String[] args) {
        Map<String, Object> result = Huffman.compress("Hello World!");
        String compressed = (String) result.get("compressed");
        Map<Character, String> codeMap = (Map<Character, String>) result.get("codeMap");
        System.out.println("Compressed text: " + compressed);

        String decompressed = Huffman.decompress(compressed, codeMap);
        System.out.println("Decompressed text: " + decompressed);
    }
}
